controller_list:
  - name: fake_base_bladder_controller
    joints:
<<<<<<< HEAD
      - bigbladder_to_head
=======
      - bigbladder_to_head
initial:
  - group: base_bladder
    pose:  home
>>>>>>> master
