<?xml version="1.0"?>
<robot name="superchick" xmlns:xacro="http://ros.org/wiki/xacro">

   <!-- General Properties -->
   <xacro:property name="bladder_pos_x" value="-0.7" />
   <xacro:property name="bladder_pos_y" value="-0.25" />

  <!-- This file contains the table and bladder descriptions -->
   <xacro:include filename="$(find superchick)/table.xacro" ns="table_ns" />
   <xacro:include filename="$(find superchick)/bladder.xacro" ns="bladder_ns" />
   <!-- <xacro:include filename="$(find superchick)/whitehead.xacro" ns="whitehead_ns" /> -->
   <xacro:include filename="$(find superchick)/headnball.xacro" ns="headnball_ns" />

   <!-- table link to bladder -->
   <joint name="table_to_bladder" type="fixed">
    <parent link="table_top"/>
    <child link="bladder_link"/>
    <limit effort="200.0" lower="0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.05" soft_upper_limit="0.05" />
    <origin xyz="${bladder_pos_x} ${bladder_pos_y} 0 " rpy="${M_PI/2} 0 ${M_PI/2}" />
   </joint>

   <!-- bladder to whitehead -->
<!--    <joint name="bladder_to_whitehead" type="planar">
    <parent link="bladder_link"/>
    <child link="whitehead_link"/>
    <limit effort="200.0" lower="0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.05" soft_upper_limit="0.05" />
    <origin xyz="0.3 ${bladder_pos_y+0.35} 1.0" rpy="${-M_PI/2} 0 0" />
   </joint> -->

   <joint name="bladder_to_headnball" type="continuous">
    <parent link="bladder_link"/>
    <child link="headnball_link"/>
    <limit effort="200.0" lower="0.1016" upper="0.1016" velocity="1.0" />
    <safety_controller k_velocity="10" k_position="15" soft_lower_limit="-0.05" soft_upper_limit="0.05" />
    <origin xyz="0.3 ${bladder_pos_y+0.35} ${0.5}" rpy="${-M_PI/2} 0 0" />
   </joint>
</robot>

<!-- ${(table_top_length/2)-0.6} -->
