<?xml version="1.0"?>
<robot name="acc16model" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Model for the Superchick Table Spec
      Author: Olalekan Ogunmolu, August 2016

        Generate urdf with 
        rosrun xacro xacro src/superchick/table.xacro > table.urdf
        Then run with 

        roslaunch superchick display.launch model:=table.urdf 
  -->

  <!-- General Properties -->
  <xacro:property name="M_PI" value="3.14159" />
  
  <!-- table top properties -->
  <xacro:property name="table_top_length" value="1.524" />
  <xacro:property name="table_top_width" value="0.6198" />
  <xacro:property name="table_top_thickness" value="0.0381" />
  <!-- table leg properties -->
  <xacro:property name="table_leg_height" value="0.635" />
  <xacro:property name="table_leg_width" value="0.1778" />
  <xacro:property name="table_leg_thickness" value="0.0254" />
  <xacro:property name="table_leg_posoffset" value="0.3302" />
  <xacro:property name="table_leg_negoffset" value="0.13208" />
  
  <!-- table leg base properties -->
  <xacro:property name="table_foot_length" value="0.5588" />
  <xacro:property name="table_foot_width" value="0.0889" />
  <xacro:property name="table_foot_thickness" value="0.05334" />

  <!-- @TODO: not to scale distance between two legs -->
  <xacro:property name="legs_xdist" value="0.4" /> 

  <!-- table cover properties -->
  <xacro:property name="table_cover_length" value="1.524" />
  <xacro:property name="table_cover_width" value="0.2794" />
  <xacro:property name="table_cover_thickness" value="${0.127+0.1}" />

  <!-- Derived Variables -->
  <material name="table_color" >
    <color rgba="0.8 0.8 0.8 1" />
  </material>

  <material name="blue">
    <color rgba="0 0 .8 1"/>
  </material>

  <material name="table_cover_color">
    <color rgba="0 ${26/255} ${51/255} 1"/>
  </material>

  <material name="dark_gray">
    <color rgba="0.156863 0.156863 0.156863 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="base_color">
    <color rgba="0 0 0 0"/>
  </material>
  
  <!-- table legs artificial base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${table_top_length} ${table_top_width} ${table_top_thickness}" />
      </geometry>
      <material name="base_color"/>
      <origin xyz="0 0 0" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <box size="${table_top_length} ${table_top_width} ${table_top_thickness}" />
      </geometry>
    </collision>
<!--     <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial> -->
  </link>

<!-- right leg -->
  <link name="right_leg">
    <visual>
      <geometry>
        <box size="${table_leg_height} ${table_leg_width} ${table_leg_thickness}"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="${table_leg_height} ${table_leg_width} ${table_leg_thickness}"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- join right leg to base -->
  <joint name="base_to_right_leg" type="fixed">
    <parent link="base_link"/>
    <child link="right_leg"/>
    <origin xyz="${(table_top_length/2)-0.0762} 0 0.3"/>
  </joint>

<!-- draw left leg -->
  <link name="left_leg">
    <visual>
      <geometry>
        <box size="${table_leg_height} ${table_leg_width} ${table_leg_thickness}"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
      <material name="dark_gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="${table_leg_height} ${table_leg_width} ${table_leg_thickness}"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
    </collision>
    <inertial>
      <mass value="10"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- join left leg to base -->
  <joint name="base_to_left_leg" type="fixed">
    <parent link="base_link"/>
    <child link="left_leg"/>
    <origin xyz="${-(table_top_length/2)+0.0762} 0 0.3"/>
  </joint>

<!-- Overlay table top -->
  <link name="table_top">
    <visual>
      <origin xyz="0 0 ${table_leg_height-0.65}" rpy="0 0 0" />
      <geometry>
        <box size="${table_top_length} ${table_top_width} ${table_top_thickness}" />
      </geometry>
      <material name="table_color"/>
      <origin xyz="0 0 ${table_leg_height-0.65}" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <box size="${table_top_length} ${table_top_width} ${table_top_thickness}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
       <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="rightleg_to_tabletop" type="fixed">
    <parent link="right_leg"/>
    <child link="table_top" />
    <origin xyz="${-(table_top_length/2)+0.0762} 0 0.35 " />
  </joint>

  <joint name="leftleg_to_tabletop" type="fixed">
    <parent link="left_leg"/>
    <child link="table_top" />
    <origin xyz="${-(table_top_length/2)+0.0762} 0 0.35 " />
  </joint>

  <link name="table_cover">
    <visual>
      <origin xyz="0 0 ${-table_top_thickness}" rpy="0 0 0" />
      <geometry>
        <box size="${table_cover_length} ${table_cover_width} ${table_cover_thickness}" />
      </geometry>
      <material name="table_cover_color"/>
      <origin xyz="0 0 ${-table_top_thickness}" rpy="0 0 0" />
    </visual>
    <collision>
      <geometry>
        <box size="${table_cover_length} ${table_cover_width} ${table_cover_thickness}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="10"/>
       <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="tablecover_to_tabletop" type="fixed">
    <parent link="table_top"/>
    <child link="table_cover"/>
    <origin xyz="0 ${(table_top_width/2)-0.08} -0.18" rpy="${-M_PI/2} 0 0 "/>
  </joint>
<!-- 
  <joint name="left_leg_to_tablecover" type="fixed">
    <parent link="table_top"/>
    <child link="left_leg"/>
    <origin xyz="0 ${(table_top_width/2)-0.08} -0.18" rpy="${-M_PI/2} 0 0 "/>
  </joint>

  <joint name="right_leg_to_tablecover" type="fixed">
    <parent link="table_top"/>
    <child link="right_leg"/>
    <origin xyz="0 ${(table_top_width/2)-0.08} -0.18" rpy="${-M_PI/2} 0 0 "/>
  </joint>
 -->
</robot>
